version: '3.3'

services:
  jupyter:
    image: jupyter/minimal-notebook
    user: root
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=token
      - GRANT_SUDO=yes
